name: Docker Image CI

on:
  push:
    branches: [ "gitactions" ]
  pull_request:
    branches: [ "gitactions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push image
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "sam08061988" --password-stdin
        docker image build -t sam08061988/flaskapi_app:latest .
        docker push sam08061988/flaskapi_app:latest
    
